#!/usr/bin/env python

import random
from pprint import pprint 

def combinaison649():
    combinaison = []
    nbiter = 7
    for i in range(1,nbiter):
	n = random.randint(1,49)
	j = 0
	while n in combinaison:
	   n = random.randint(1,49)
	   if j > nbiter: 
	      break 
	   j += 1
 	combinaison.append(n)
        random.shuffle(combinaison)
    return sorted(combinaison)

c649 = combinaison649()

pprint(c649)
print(len(set(c649)))
